name: Deploy Svelte app to Github Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_PATH: "." # default value when not using subfolders
  # BUILD_PATH: subfolder

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.BUILD_PATH }}
      - name: Build Svelte app
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}
      - name: List repo files
        run: ls -la
        working-directory: ${{ env.BUILD_PATH }}
      - name: List artifact files
        run: ls -la
        working-directory: ${{ env.BUILD_PATH }}/dist
#      - name: Copy data files from repo to dist dir
#        run: |
#          mkdir ./dist/data
#          cp -R ./data/* ./dist/data/
#        working-directory: ${{ env.BUILD_PATH }}
      - name: List artifact files
        run: ls -la
        working-directory: ${{ env.BUILD_PATH }}/dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
